### ISSUE TITLE
How can I clear invalid connection?

### ISSUE THREAD

**Issue by dicome** [elasticsearch/docs#18]
Server have many invalid connection when the network breakdown coming.

I use transport client  to connect  a elasticserach cluster ,I could see 14 connection on server-side.
When network breakdown ,the client will reconnect to the server .
Then I can see 28 connection on server-side.

How can I clear invalid connection ?

**Comment by dicome** [comment]
I mean is   inactive connections.

**Comment by clintongormley** [comment]
Hi @dicome 

Please ask questions like this on the mailing list instead.
