### ISSUE TITLE
cat-segments docs are missing in current version of the docs

### ISSUE THREAD

**Issue by abraxxa** [elasticsearch/docs#20]
There is http://www.elasticsearch.org/guide/en/elasticsearch/reference/1.x/cat-segments.html but no http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/cat-segments.html

**Comment by javanna** [comment]
Thanks for raising this @abraxxa we recently added docs for cat segments but only to 1.x and master, we should backport it to `1.4` branch too. See https://github.com/elasticsearch/elasticsearch/pull/9179 .

**Comment by clintongormley** [comment]
I've backported to 1.3 and 1.4
